import pandas as pd
df = pd.read_csv('data/cities/delhi/canonical/water_demand.csv')
df['Date'] = pd.to_datetime(df['Date'])
print('Unique dates around 2021-06-17:')
mask = df['Date'].between('2021-06-10', '2021-06-25')
print(df.loc[mask, 'Date'].dt.strftime('%Y-%m-%d').tolist())
print()
print('Rows:', len(df))
print('First 5 dates:', df['Date'].head().dt.strftime('%Y-%m-%d').tolist())
print('Last 5 dates:', df['Date'].tail().dt.strftime('%Y-%m-%d').tolist())
